title : Hemi Luan
tagline: MSCBM
author :
  name : Hemi Luan
  email : hm-luan@msn.com

permalink: /:year/:month/:day/:title.html
redirects: yes
exclude: [ _posts/source/, _posts/_private/ ]

plugins:
  - jekyll-pandoc

markdown: pandoc
pandoc:
   extensions:
      - mathjax

highlighter: pygments
source: .
lsi: True

pageviews: yes    ## toggle on sidebar pageviews 
gitstamps: yes
repo: https://github.com/13479776/mscbm.github.io # used in linking history

baseurl: '/'

#markdown: redcarpet
#redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
